import fs from 'fs'
import path from 'path'
import type { AnalysisSession, AutonomyLevel } from '../types/autonomy.js'
import { AUTONOMY_LEVELS, EXPOSURE_EMOJI, EXPOSURE_LABEL, LEVEL_LABELS } from '../types/autonomy.js'

export function exportMarkdown(session: AnalysisSession): string {
  const lines: string[] = []
  const map = session.autonomyMap

  lines.push(`# AI Autonomy Mapping Report: ${session.role}`)
  lines.push(``)
  if (session.context) lines.push(`> **Context**: ${session.context}\n`)
  lines.push(`**Generated**: ${new Date(session.createdAt).toLocaleString()}`)
  lines.push(`**Target Autonomy Level**: ${session.autonomyTarget} — ${LEVEL_LABELS[session.autonomyTarget]}`)
  lines.push(``)
  lines.push(`## Heatmap`)
  lines.push(``)

  const header = `| Capability | Zone | ${AUTONOMY_LEVELS.join(' | ')} |`
  const sep = `| --- | --- | ${AUTONOMY_LEVELS.map(() => '---').join(' | ')} |`
  lines.push(header)
  lines.push(sep)

  for (const { capability: cap, scores } of map) {
    const cells = AUTONOMY_LEVELS.map((l) => {
      const s = scores[l as AutonomyLevel]
      return `${EXPOSURE_EMOJI[s]} ${s}`
    })
    lines.push(`| ${cap.name} | ${cap.zone} | ${cells.join(' | ')} |`)
  }

  lines.push(``)
  lines.push(`## Legend`)
  lines.push(``)
  for (const [k, v] of Object.entries(EXPOSURE_EMOJI)) {
    lines.push(`- ${v} **${k}** — ${EXPOSURE_LABEL[k as keyof typeof EXPOSURE_EMOJI]}`)
  }

  lines.push(``)
  lines.push(`## Capability Details`)
  lines.push(``)
  for (const { capability: cap } of map) {
    lines.push(`### ${cap.name} (${cap.zone})`)
    if (cap.notes) lines.push(`*${cap.notes}*`)
    const flags = []
    if (cap.repetitive)   flags.push('Repetitive')
    if (cap.dataRich)     flags.push('Data-rich')
    if (cap.highJudgment) flags.push('High judgment')
    if (cap.highRisk)     flags.push('High risk')
    if (flags.length) lines.push(`**Flags**: ${flags.join(', ')}`)
    lines.push(``)
  }

  lines.push(`---`)
  lines.push(`*Generated by AI Autonomy Mapper CLI*`)
  return lines.join('\n')
}

export function exportCSV(session: AnalysisSession): string {
  const map = session.autonomyMap
  const header = `Capability,Zone,${AUTONOMY_LEVELS.join(',')},Flags\n`
  const rows = map.map(({ capability: cap, scores }) => {
    const scoreStrs = AUTONOMY_LEVELS.map((l) => scores[l as AutonomyLevel])
    const flags = []
    if (cap.repetitive)   flags.push('repetitive')
    if (cap.dataRich)     flags.push('data-rich')
    if (cap.highJudgment) flags.push('high-judgment')
    if (cap.highRisk)     flags.push('high-risk')
    return `"${cap.name}",${cap.zone},${scoreStrs.join(',')},${flags.join(';') || '-'}`
  })
  return header + rows.join('\n')
}

export function saveToFile(filename: string, content: string, format: 'md' | 'json' | 'csv'): string {
  const outputDir = path.join(process.cwd(), 'output')
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true })
  }

  const ext = format === 'md' ? '.md' : format === 'csv' ? '.csv' : '.json'
  const filepath = path.join(outputDir, `${filename}${ext}`)
  fs.writeFileSync(filepath, content, 'utf-8')
  return filepath
}
