import { useAnalysisStore } from '../store'
import {
  AUTONOMY_LEVELS,
  EXPOSURE_EMOJI,
  EXPOSURE_LABEL,
  LEVEL_LABELS,
} from '../types/autonomy'
import type { AutonomyLevel, AutonomyMapping, ExposureScore } from '../types/autonomy'
import { numericScore } from '../engine/autonomy-engine'

// ─── Markdown export ──────────────────────────────────────────────────────────
function buildMarkdown(
  role: string,
  context: string | undefined,
  target: AutonomyLevel,
  map: AutonomyMapping[],
): string {
  const lines: string[] = []
  lines.push(`# AI Autonomy Mapping Report: ${role}`)
  lines.push(``)
  if (context) lines.push(`> **Context**: ${context}\n`)
  lines.push(`**Generated**: ${new Date().toLocaleString()}`)
  lines.push(`**Target Autonomy Level**: ${target} — ${LEVEL_LABELS[target]}`)
  lines.push(``)
  lines.push(`## Heatmap`)
  lines.push(``)

  const header = `| Capability | Zone | ${AUTONOMY_LEVELS.join(' | ')} |`
  const sep    = `| --- | --- | ${AUTONOMY_LEVELS.map(() => '---').join(' | ')} |`
  lines.push(header)
  lines.push(sep)

  for (const { capability: cap, scores } of map) {
    const cells = AUTONOMY_LEVELS.map((l: AutonomyLevel) => {
      const s: ExposureScore = scores[l]
      return `${EXPOSURE_EMOJI[s]} ${s}`
    })
    lines.push(`| ${cap.name} | ${cap.zone} | ${cells.join(' | ')} |`)
  }

  lines.push(``)
  lines.push(`## Legend`)
  lines.push(``)
  for (const [k, v] of Object.entries(EXPOSURE_EMOJI)) {
    lines.push(`- ${v} **${k}** — ${EXPOSURE_LABEL[k as ExposureScore]}`)
  }

  lines.push(``)
  lines.push(`## Capability Details`)
  lines.push(``)
  for (const { capability: cap } of map) {
    lines.push(`### ${cap.name} (${cap.zone})`)
    if (cap.notes) lines.push(`*${cap.notes}*`)
    const flags = []
    if (cap.repetitive)   flags.push('Repetitive')
    if (cap.dataRich)     flags.push('Data-rich')
    if (cap.highJudgment) flags.push('High judgment')
    if (cap.highRisk)     flags.push('High risk')
    if (flags.length) lines.push(`Flags: ${flags.join(', ')}`)
    lines.push(``)
  }

  lines.push(`---`)
  lines.push(`*Generated by AI Autonomy Mapper*`)
  return lines.join('\n')
}

function downloadText(filename: string, content: string) {
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}

// ─── Stats helpers ─────────────────────────────────────────────────────────────
function avgScoreAtTarget(
  map: AutonomyMapping[],
  target: AutonomyLevel,
): { avg: number; highAutomation: number; highHuman: number; total: number } {
  const total = map.length
  if (!total) return { avg: 0, highAutomation: 0, highHuman: 0, total: 0 }
  let sum = 0
  let highAutomation = 0
  let highHuman = 0
  for (const { scores } of map) {
    const s: ExposureScore = scores[target]
    const n = numericScore(s)
    sum += n
    if (n >= 3) highAutomation++
    if (n <= 1) highHuman++
  }
  return { avg: sum / total, highAutomation, highHuman, total }
}

export default function ResultsPage() {
  const session  = useAnalysisStore((s) => s.session)
  const setPhase = useAnalysisStore((s) => s.setPhase)
  const reset    = useAnalysisStore((s) => s.reset)

  const map    = session?.autonomyMap ?? []
  const target = session?.autonomyTarget ?? 'L3'

  const stats = avgScoreAtTarget(map, target)

  function handleExport() {
    const md = buildMarkdown(
      session?.role ?? 'Unknown',
      session?.context,
      target,
      map,
    )
    const slug = (session?.role ?? 'role').toLowerCase().replace(/\s+/g, '-')
    downloadText(`ai-autonomy-${slug}-${target}.md`, md)
  }

  function handleExportJSON() {
    const blob = new Blob([JSON.stringify(session, null, 2)], { type: 'application/json' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    const slug = (session?.role ?? 'role').toLowerCase().replace(/\s+/g, '-')
    a.href = url
    a.download = `ai-autonomy-${slug}-${target}.json`
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="max-w-4xl mx-auto">
      <h2 className="text-2xl font-bold text-gray-800 mb-1">Analysis Report</h2>
      <p className="text-gray-500 text-sm mb-6">
        Role: <span className="font-semibold text-gray-700">{session?.role}</span>
        {' · '}Target: <span className="font-semibold text-brand">{target}</span>
      </p>

      {/* Summary cards */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-8">
        <StatCard label="Total Capabilities" value={String(stats.total)} />
        <StatCard label="Avg Exposure Score" value={stats.avg.toFixed(1)} sub={`at ${target}`} />
        <StatCard label="High Automation" value={String(stats.highAutomation)} sub={`≥ MOSTLY_AI at ${target}`} color="text-orange-600" />
        <StatCard label="Human-centric" value={String(stats.highHuman)} sub={`≤ MOSTLY_HUMAN at ${target}`} color="text-green-600" />
      </div>

      {/* Target level info */}
      <div className="bg-blue-50 border border-blue-200 rounded-xl p-4 mb-6">
        <p className="text-sm font-bold text-blue-800 mb-0.5">{target} — {LEVEL_LABELS[target]}</p>
        <p className="text-xs text-blue-700">
          At this autonomy level, {stats.highAutomation} of {stats.total} capabilities are highly automatable 
          and {stats.highHuman} remain firmly human-centric.
        </p>
      </div>

      {/* Capability summary table */}
      <div className="overflow-x-auto rounded-xl border border-gray-200 mb-8">
        <table className="w-full text-sm">
          <thead className="bg-gray-50">
            <tr>
              <th className="text-left px-4 py-3 text-xs text-gray-500 uppercase tracking-wide">Capability</th>
              <th className="px-3 py-3 text-xs text-gray-500 uppercase tracking-wide text-center">Zone</th>
              <th className="px-3 py-3 text-xs text-brand uppercase tracking-wide text-center">Score at {target}</th>
              <th className="text-left px-4 py-3 text-xs text-gray-500 uppercase tracking-wide">Flags</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-gray-100">
            {map.map(({ capability: cap, scores }) => {
              const score: ExposureScore = scores[target as AutonomyLevel]
              const flags = []
              if (cap.repetitive)   flags.push('🔁 Repetitive')
              if (cap.dataRich)     flags.push('📊 Data-rich')
              if (cap.highJudgment) flags.push('🧠 High Judgment')
              if (cap.highRisk)     flags.push('⚠️ High Risk')
              return (
                <tr key={cap.id} className="hover:bg-gray-50">
                  <td className="px-4 py-3 font-medium text-gray-800">{cap.name}</td>
                  <td className="px-3 py-3 text-center text-xs text-gray-500">{cap.zone}</td>
                  <td className="px-3 py-3 text-center">
                    <span className="text-xl">{EXPOSURE_EMOJI[score]}</span>
                    <div className="text-xs text-gray-500">{score.replace('_', ' ')}</div>
                  </td>
                  <td className="px-4 py-3 text-xs text-gray-500">{flags.join(' · ') || '—'}</td>
                </tr>
              )
            })}
          </tbody>
        </table>
      </div>

      {/* Actions */}
      <div className="flex flex-wrap gap-3 mb-6">
        <button
          onClick={handleExport}
          className="flex items-center gap-2 bg-brand text-white px-5 py-2.5 rounded-lg font-semibold text-sm hover:bg-brand-dark transition-colors"
        >
          ↓ Export Markdown
        </button>
        <button
          onClick={handleExportJSON}
          className="flex items-center gap-2 border border-brand text-brand px-5 py-2.5 rounded-lg font-semibold text-sm hover:bg-brand-light transition-colors"
        >
          ↓ Export JSON
        </button>
        <button
          onClick={() => setPhase('heatmap')}
          className="px-5 py-2.5 rounded-lg border border-gray-300 text-gray-700 text-sm hover:bg-gray-50"
        >
          ← Back to Heatmap
        </button>
        <button
          onClick={reset}
          className="px-5 py-2.5 rounded-lg border border-gray-300 text-gray-500 text-sm hover:bg-gray-50 ml-auto"
        >
          Start New Analysis
        </button>
      </div>
    </div>
  )
}

function StatCard({
  label,
  value,
  sub,
  color = 'text-gray-800',
}: {
  label: string
  value: string
  sub?: string
  color?: string
}) {
  return (
    <div className="bg-white border border-gray-200 rounded-xl p-4">
      <p className="text-xs text-gray-500 mb-1">{label}</p>
      <p className={`text-3xl font-bold ${color}`}>{value}</p>
      {sub && <p className="text-xs text-gray-400 mt-0.5">{sub}</p>}
    </div>
  )
}
